### PR TITLE
fix(rest): add endpoint to  merge two releases.

### LINKED ISSUE #3160: feat(Release): Rest API needed to merge releases for a single component
### Description

Need a feature to merge releases under a single component.

### PR DESCRIPTION
**Pull request by nikkuma7**
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

> Please provide a summary of your changes here.
> * Which issue is this pull request belonging to and how is it solving it? (*Refer to issue here*)
> * Did you add or update any new dependencies that are required for your change?

Closes #3160 

### How To Test?

PATCH: http://localhost:8080/resource/api/releases/mergereleases?mergeTargetId=730e1c64f66715a2868ced346b00697f&mergeSourceId=730e1c64f66715a2868ced346b005dc6

Body :
```json
{
  "name": "Final Release Name",
  "createdOn": "2025-05-14",
  "createdBy": "emailId",
  "attachments": [
    {
      "attachmentContentId": "att1",
      "filename": "saveme.txt"
    }
  ]
}
```
> How should these changes be tested by the reviewer?
> Have you implemented any additional tests?

### Checklist
Must:
- [ ] All related issues are referenced in commit messages and in PR

### CODE REVIEW

File: rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/ReleaseMergeSelector.java [hunk 1]
```diff
@@ -0,0 +1,26 @@
...
+
+package org.eclipse.sw360.rest.resourceserver.release;
+
+import java.util.Arrays;
+
+import org.eclipse.sw360.datahandler.thrift.ThriftUtils;
+import org.eclipse.sw360.datahandler.thrift.components.Release;
+import org.jetbrains.annotations.NotNull;
+
+public class ReleaseMergeSelector extends Release {
```
Comment (GMishx) [inline rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/ReleaseMergeSelector.java:19]: Please add Jackson mixin for this class.

File: rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/Sw360ReleaseService.java [hunk 2]
```diff
@@ -1419,4 +1422,38 @@ private void addLicenseInfoResultToJsonSerializableLicensesList(LicenseInfoParsi
...
+
+        validateReleaseMergeSelection(releaseSelection);
+        ComponentService.Iface sw360ComponentClient = getThriftComponentClient();
+        RequestStatus requestStatus = sw360ComponentClient.mergeReleases(mergeTargetId, mergeSourceId, releaseSelection,
+                sw360User);
+
+        if (requestStatus == RequestStatus.IN_USE) {
+            throw new BadRequestClientException("Release already in use.");
+        } else if (requestStatus == RequestStatus.FAILURE) {
+            throw new BadRequestClientException("Cannot merge these releases.");
```
Comment (GMishx) [inline rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/Sw360ReleaseService.java:1437]: Should be an internal server error.
```suggestion
            throw new SW360Exception("Cannot merge these releases.");
```

**Review by GMishx — CHANGES_REQUESTED** [review]

File: rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/ReleaseController.java [hunk 3]
```diff
@@ -1834,4 +1835,55 @@ public ResponseEntity<List<Map<String,String>>> getReleaseLicenseInfo(
...
+                    sw360User);
+
+            return new ResponseEntity<>(requestStatus, HttpStatus.OK);
+        } catch (SW360Exception e) {
+            return new ResponseEntity("Unable to merge releases: " + e.getMessage(), HttpStatus.INTERNAL_SERVER_ERROR);
+        } catch (AccessDeniedException e) {
+            return new ResponseEntity("Access denied: " + e.getMessage(), HttpStatus.FORBIDDEN);
+        } catch (TException e) {
+            return new ResponseEntity("Internal error: " + e.getMessage(), HttpStatus.INTERNAL_SERVER_ERROR);
+        }
```
Comment (GMishx) [inline rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/ReleaseController.java:1887]: Please throw appropriate exceptions!

Comment (GMishx) [reply rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/release/ReleaseController.java:1887]: They are thrown in Service class, why are you capturing them here again?

**Review by GMishx — CHANGES_REQUESTED** [review]

**Review by GMishx — DISMISSED** [review]
Changes looks good.

**Comment by keerthi-bl** [comment]
@nikkuma7 

### Observation while testing the PR.

1. There are more parameters which are mandatory while hitting the api - **Version** and **ComponentId**
2. After successful merge , do we need to return merged release data ? or Only success message?
3. Multiple time if i try to merge the same release id - need a proper message like - source/target release id not exit something like that ~~ (currently throwing internal server error only)
4. Need to update the example in the end point , by adding componentId and version. 
image
5. validating version and componentId should be handled, which is not currently present in the end point.



FYI, @GMishx

**Review by GMishx — DISMISSED** [review]
