### PR TITLE
fix(rest): Add logic to delete open clearing requests from request tab, when the project has deleted

### LINKED ISSUE #3676: fix(rest): Add logic to delete open clearing requests from request tab, when the project has deleted
### Description

When a project with open clearing requests is deleted, the clearing requests remain in an open state (not approved/declined). Ideally, if the project is deleted, the clearing requests have no further use and should be removed.

Please describe your situation in few words here.

#### Steps followed and expected result

Describe the steps followed by you and your expected results after following the steps.

#### Screenshots ( if applicable )

Add screenshots to help explain your problem.

### PR DESCRIPTION
**Pull request by nikkuma7**
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

> Please provide a summary of your changes here.
> * Which issue is this pull request belonging to and how is it solving it? (*Refer to issue here*)
> * Did you add or update any new dependencies that are required for your change?

Issue: Closes: Closes #3676 

### How To Test?

**Test Scenario 1:** Delete Project with Open Clearing Request
1. Navigate to Projects page
2. Create a new test project or select an existing project
3. Create a clearing request for this project (if not already present)
4. Verify the clearing request appears in the "Clearing Requests" tab/page
5. Delete the project from the Projects page
6. Navigate to the "Clearing Requests" tab
**Expected Result:** The clearing request associated with the deleted project should be automatically removed from the list

**Test Scenario 2:** Verify No Impact on Other Clearing Requests

1. Create multiple projects with clearing requests
2. Delete only one project
**Expected Result:** Only the clearing request(s) for the deleted project should be removed; other clearing requests should remain intact

> How should these changes be tested by the reviewer?
> Have you implemented any additional tests?

### Checklist
Must:
- [ ] All related issues are referenced in commit messages and in PR

### CODE REVIEW

File: backend/moderation/src/main/java/org/eclipse/sw360/moderation/db/ModerationDatabaseHandler.java [hunk 1]
```diff
@@ -308,18 +308,58 @@ public RequestStatus updateClearingRequest(ClearingRequest request, User user, S
...
-                .append("</b> associated with CR is deleted!").toString());
-        comment.setCommentedBy(user.getEmail());
-        comment.setAutoGenerated(true);
-        comment.setCommentedOn(System.currentTimeMillis());
-        clearingRequest.unsetProjectId();
-        clearingRequest.addToComments(comment);
-        clearingRequest.setModifiedOn(System.currentTimeMillis());
-        clearingRequest.unsetPriority();
-        clearingRequestRepository.update(clearingRequest);
+       try {
```
Comment (GMishx) [inline backend/moderation/src/main/java/org/eclipse/sw360/moderation/db/ModerationDatabaseHandler.java]: Please do not use such a big try/catch block. Make it smaller with relevant catches.

File: backend/moderation/src/main/java/org/eclipse/sw360/moderation/db/ModerationDatabaseHandler.java [hunk 2]
```diff
@@ -308,18 +308,58 @@ public RequestStatus updateClearingRequest(ClearingRequest request, User user, S
...
+            ClearingRequest clearingRequest = clearingRequestRepository.get(project.getClearingRequestId());
+            if (clearingRequest == null) {
+                log.info("Clearing request " + project.getClearingRequestId() + " not found for project " + project.getId() + " deletion. It may have already been deleted.");
+                return;
+            }
+            Comment comment = new Comment().setText(new StringBuilder("Clearing Request is orphaned, as project (name): <b>")
+                    .append(SW360Utils.printName(project))
+                    .append("</b> associated with CR is deleted!").toString());
```
Comment (GMishx) [inline backend/moderation/src/main/java/org/eclipse/sw360/moderation/db/ModerationDatabaseHandler.java]: `StringBuilder` is not required here. Can simply be done with a normal
```java
"CR orphan " + SW360Utils.printName(project) + " <end>"
```
string concatenations.

File: backend/moderation/src/main/java/org/eclipse/sw360/moderation/db/ModerationDatabaseHandler.java [hunk 3]
```diff
@@ -308,18 +308,58 @@ public RequestStatus updateClearingRequest(ClearingRequest request, User user, S
...
+            comment.setCommentedBy(user.getEmail());
+            comment.setAutoGenerated(true);
+            comment.setCommentedOn(System.currentTimeMillis());
+            clearingRequest.unsetProjectId();
+            clearingRequest.addToComments(comment);
+            clearingRequest.setModifiedOn(System.currentTimeMillis());
+            clearingRequest.unsetPriority();
+            clearingRequestRepository.update(clearingRequest);
+        } catch (Exception e) {
```
Comment (GMishx) [inline backend/moderation/src/main/java/org/eclipse/sw360/moderation/db/ModerationDatabaseHandler.java]: Please try to capture scoped exceptions. Catching `Exception` should be avoided.

File: rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java [hunk 4]
```diff
@@ -1786,6 +1826,23 @@ public ResponseEntity<EntityModel<Project>> patchProject(
...
+        try {
+            clearingRequest = moderationClient.getClearingRequestByProjectId(id, user);
+        } catch (TException e) {
+            // If there's an error getting the clearing request, assume there isn't one
+            log.info("No clearing request found for project: " + id + " (exception: " + e.getMessage() + ")");
+        }
+        // Only set hasOpenClearingRequest to true if we have a non-null clearing request that isn't closed
+        hasOpenClearingRequest = clearingRequest != null && !isClosedClearingRequest(clearingRequest);
+        if (hasOpenClearingRequest) {
+            log.warn("Project has an open clearing request. Edit may require special handling.");
```
Comment (GMishx) [inline rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/ProjectController.java]: There is no special action done here after checking if the CR exists or the CR is open.

**Comment by nikkuma7** [comment]
@GMishx , Comment addressed.

**Review by GMishx — APPROVED** [review]
Changes looks good.

**Comment by GMishx** [comment]
@keerthi-bl please help test this PR.

**Comment by keerthi-bl** [comment]
> @keerthi-bl please help test this PR.

Sure, Taken it for testing.

**Comment by amritkv** [comment]
Hey @keerthi-bl  and @nikkuma7 !
Here we need to test the below mentioned scenario :

- If a CR is already in a state other than `OPEN` or `IN_PROGRESS`, what will happen with them when we try to delete a project with CR.

**Comment by keerthi-bl** [comment]
> Hey @keerthi-bl and @nikkuma7 ! Here we need to test the below mentioned scenario :
> 
> * If a CR is already in a state other than `OPEN` or `IN_PROGRESS`, what will happen with them when we try to delete a project with CR.

As per the requirement, If any CR under open clearing request tab should get deleted if it associated with deleted project.
If CR is rejected/Closed and fall under Closed CR - should not get deleted if associated project get deleted.

**Comment by keerthi-bl** [comment]
Test sucessful, moving to ready state.
