### PR TITLE
fix(nouveau): add ConflictException retry to putNouveauDesignDocument

### LINKED ISSUE #3824: putNouveauDesignDocument missing ConflictException retry causes concurrent WAR startup failures
# Description

Similar to #3822 (`putDesignDocument` in `DatabaseConnectorCloudant`), `putNouveauDesignDocument` in `LuceneAwareCouchDbConnector` has the same missing `ConflictException` retry, causing the same concurrent WAR startup failure.

**Affected file:**
`libraries/nouveau-handler/src/main/java/org/eclipse/sw360/nouveau/LuceneAwareCouchDbConnector.java`

## How to reproduce

1. Deploy a full SW360 instance with multiple WARs (e.g. `projects.war`, `components.war`, `vendors.war`).
2. Restart Tomcat so all WARs initialize concurrently.
3. Observe servlet initialization failures in Tomcat logs:

```
com.ibm.cloud.sdk.core.service.exception.ConflictException: conflict: Document update conflict.
    at LuceneAwareCouchDbConnector$NouveauAwareDatabase.putNouveauDesignDocument(...)
    at NouveauLuceneAwareDatabaseConnector.addDesignDoc(...)
    at ComponentSearchHandler.<init>(...)
    at ComponentHandler.<init>(...)
```

1. Observe that affected endpoints return 404 permanently until the next restart.

**Expected:** All WARs initialize successfully regardless of start order.

**Actual:** An unhandled `ConflictException` propagates up through `addDesignDoc` → search handler constructor → service handler constructor → `servlet init()`. Tomcat marks the context as failed. Worse than #3822: on failure, a `RuntimeException` is explicitly thrown, making the crash guaranteed rather than incidental.

## Root cause

`putNouveauDesignDocument` reads the current `_rev`, builds `PutDesignDocumentOptions`, and writes with no conflict handling. When `projects.war`, `components.war`, and `vendors.war` all start concurrently:

1. All three read `_rev = X` for `_design/lucene` in `sw360db`
2. One writes successfully → `_rev = X+1`
3. The others write with stale `_rev = X` → `ConflictException`
4. No retry → `RuntimeException` thrown → servlet init fails → 404

Every search handler (`ProjectSearchHandler`, `ComponentSearchHandler`, `ReleaseSearchHandler`, `VendorSearchHandler`, and 9 others) uses the same `DDOC_NAME = "lucene"` on the same `COUCH_DB_DATABASE`, so any two WARs starting at the same time will trigger this.

### PR DESCRIPTION
**Pull request by Shivamrut**
Fixes #3824

## Summary

`putNouveauDesignDocument` in `LuceneAwareCouchDbConnector` has the same missing `ConflictException` retry as #3822/#3823. All 13 search handlers share `DDOC_NAME = "lucene"` on the same `COUCH_DB_DATABASE`, so any two WARs starting concurrently (e.g. `projects.war`, `components.war`, `vendors.war`) race on writing the same `_design/lucene` document, causing servlet initialization to fail and endpoints to return 404 permanently.

## Fix

On `ConflictException | TooManyRequestsException`, the code now sleeps 100 ms, re-fetches the latest `_rev`, updates `designDocument` in-place, and retries the PUT once — reusing the existing `designDocumentOptions` without rebuilding it, since `PutDesignDocumentOptions` holds a direct reference to `designDocument`. This is consistent with the pattern in `DatabaseConnectorCloudant` fixed in #3823.

## Suggested Reviewers

@GMishx @rudra-superrr @bibhuti230185 @amritkv @EttingerK

## Checklist

Must:
- [x] All related issues are referenced in commit messages and in PR

### CODE REVIEW

File: libraries/nouveau-handler/src/main/java/org/eclipse/sw360/nouveau/LuceneAwareCouchDbConnector.java [hunk 1]
```diff
@@ -148,9 +150,29 @@ public boolean putNouveauDesignDocument(
...
-            DocumentResult response =
-                    this.putDesignDocument(designDocumentOptions)
+            DocumentResult response;
+            try {
+                response = this.putDesignDocument(designDocumentOptions)
+                        .execute().getResult();
+            } catch (ConflictException | TooManyRequestsException e) {
+                try {
+                    Thread.sleep(100);
+                    NouveauDesignDocument refreshedDoc;
```
Comment (GMishx) [inline libraries/nouveau-handler/src/main/java/org/eclipse/sw360/nouveau/LuceneAwareCouchDbConnector.java]: Same as #3823, please reuse objects.

**Comment by Shivamrut** [comment]
@GMishx Please review now, only used existing objects
