### PR TITLE
Fix project clearing report issues

### LINKED ISSUE #591: Fix project clearing report
- Programming language is always N/A
- Duplicate entries in table under section 3.1 Common Rules

See also #526

### PR DESCRIPTION
**Pull request by manhuu14**
- Add missing projectResponsible to attendees table
- Fix programming language showing N/A by fetching full release
- Fix duplicate entries in section 3.1 Common Rules

Fixes #591

### CODE REVIEW

**Comment by GMishx** [comment]
Thanks for your contribution @manhuu14 . However, I would like to deffer this PR until after the release.

File: backend/licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/outputGenerators/DocxGenerator.java [hunk 1]
```diff
@@ -355,6 +355,20 @@ private void fillAttendeesTable(XWPFDocument document, Project project) throws X
                 addFormattedTextInTableCell(row.addNewTableCell(), "Owner");
             }
         }
+        if (project.isSetProjectResponsible() && !project.getProjectResponsible().isEmpty()) {
+            User responsible = null;
+            try {
+                responsible = userClient.getByEmail(project.getProjectResponsible());
+            } catch (TException te) {
+                // a resulting null user object is handled below
```
Comment (keerthi-bl) [inline backend/licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/outputGenerators/DocxGenerator.java:363]: Add proper exception handling with message in Catch block.

File: backend/licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/outputGenerators/DocxGenerator.java [hunk 2]
```diff
@@ -567,6 +581,18 @@ private void fillDevelopmentDetailsTable(XWPFDocument document, Project project,
...
+            if (r.getLanguagesSize() == 0 && r.getOperatingSystemsSize() == 0 && r.getSoftwarePlatformsSize() == 0) {
+                try {
+                    org.eclipse.sw360.datahandler.thrift.components.ComponentService.Iface componentClient =
+                            new ThriftClients().makeComponentClient();
+                    Release fullRelease = componentClient.getReleaseById(r.getId(), user);
+                    if (fullRelease != null) {
+                        r = fullRelease;
+                    }
+                } catch (TException e) {
+                    // fall back to the summary release if fetch fails
```
Comment (keerthi-bl) [inline backend/licenseinfo/src/main/java/org/eclipse/sw360/licenseinfo/outputGenerators/DocxGenerator.java:593]: Add proper exception handling with message in Catch block.

**Comment by nikkuma7** [comment]
we need to fix this issue : https://github.com/eclipse-sw360/sw360-frontend/issues/1587
