### PR TITLE
fix(importCDX) : Fix package's linked release updation when an SBOM is imported

### LINKED ISSUE #2428: Existing package getting updated on importing an SBOM that contains a package with same PURL causing inconsistency in other projects.
If an SBOM is imported which contains a pkg that is already present in sw360, then the existing pkg is linked to the release created by the imported SBOM causing inconsistency in all other projects where the pkg already exists. 
For example : 
pkg **color-name (1.1.3)** was already present in the database linked to release **colorjs.color-name (1.1.3)**

An SBOM imported with a pkg with same PURL as below: 

image
Now pkg is linked to the new release but in all other projects created before the old release is linked causing inconsistency.
 
image

### PR DESCRIPTION
**Pull request by akshitjoshii**
closes #2428
Now when an SBOM is imported containing a duplicate pkg, the existing pkg's linked release would not be modified. 
For example : 
If this an SBOM that contains a duplicate pkg but different VCS : 
akshitPR1
 
The existing pkg : **chartjs.chartjs-color-string (0.6.0)** along with it's release is linked to the project along with the new release that is created from the SBOM. 

2024-04-30 14_35_10-SW360_NEW  Running  - Oracle VM VirtualBox

2024-04-30 14_38_00-SW360_NEW  Running  - Oracle VM VirtualBox
 
With this change the projects that were using the particular pkg won't be affected and there won't be an inconsistency in them.

### CODE REVIEW

**Comment by afsahsyeda** [comment]
@akshitjoshii How does this behave in case of Orphan packages? (No linked release in SW360, but VCS present in imported SBOM)

**Comment by afsahsyeda** [comment]
@sameed20 Kindly test this PR.

**Comment by sameed20** [comment]
@akshitjoshii @afsahsyeda If an orphaned package exists in SW360, and subsequently, an attempt is made to import the same package using the CycloneDX SBOM, and if the imported SBOM contains VCS information for this package, then this orphan should be linked to the release which is being created during the import.
pr_ak_test

Like in this example before importing an SBOM angular-mocks was an orphan package in SW360. After, importing an SBOM which contains a VCS for this package, angular-mocks package is still not getting linked to imported release.

**Comment by akshitjoshii** [comment]
@sameed20 Pls test,addressed the above comments.

**Comment by sameed20** [comment]
If an SBOM contains a VCS for an orphan package in SW360, then that orphan package gets linked to the release created from the SBOM. However, if any other project was using this orphan package before the linking of this release, then this newly linked release will not appear in the License Clearing tab of that project.

@akshitjoshii is this the intended behavior ?

**Comment by akshitjoshii** [comment]
Yes, this is intended as the release information was not present in the SBOM of the project and was used in the project without source information.

**Comment by sameed20** [comment]
Test Successful

File: backend/src-common/src/main/java/org/eclipse/sw360/cyclonedx/CycloneDxBOMImporter.java [hunk 1]
```diff
@@ -647,9 +647,13 @@ private Map<String, String> importAllComponentsAsPackages(Map<String, List<org.c
                             if (AddDocumentRequestStatus.DUPLICATE.equals(pkgAddSummary.getRequestStatus())) {
                                 Package dupPkg = packageDatabaseHandler.getPackageById(pkg.getId());
                                 if (!release.getId().equals(dupPkg.getReleaseId())) {
+                                    /* check if duPkg is orphan pkg or not */
+                                    if(!CommonUtils.isNotNullEmptyOrWhitespace(dupPkg.getReleaseId())){
```
Comment (afsahsyeda) [inline backend/src-common/src/main/java/org/eclipse/sw360/cyclonedx/CycloneDxBOMImporter.java:651]: add this on line 649 in the same If condition separated by & operator. Also use CommonUtils.isNullEmptyOrWhitespace instead.

**Review by afsahsyeda — CHANGES_REQUESTED** [review]

File: backend/src-common/src/main/java/org/eclipse/sw360/cyclonedx/CycloneDxBOMImporter.java [hunk 2]
```diff
@@ -647,9 +647,13 @@ private Map<String, String> importAllComponentsAsPackages(Map<String, List<org.c
...
+                                        dupPkg.setReleaseId(release.getId());
```
Comment (afsahsyeda) [inline backend/src-common/src/main/java/org/eclipse/sw360/cyclonedx/CycloneDxBOMImporter.java:652]: Store release.getId() and dupPkg.getReleaseId() in variables to avoid repeated function calls.

**Review by afsahsyeda — CHANGES_REQUESTED** [review]

File: backend/src-common/src/main/java/org/eclipse/sw360/cyclonedx/CycloneDxBOMImporter.java [hunk 3]
```diff
@@ -646,10 +646,14 @@ private Map<String, String> importAllComponentsAsPackages(Map<String, List<org.c
                             pkg.setId(pkgAddSummary.getId());
                             if (AddDocumentRequestStatus.DUPLICATE.equals(pkgAddSummary.getRequestStatus())) {
                                 Package dupPkg = packageDatabaseHandler.getPackageById(pkg.getId());
-                                if (!release.getId().equals(dupPkg.getReleaseId())) {
-                                    log.error("Release Id of Package from BOM: '%s' and Database: '%s' is not equal!", release.getId(), dupPkg.getReleaseId());
-                                    dupPkg.setReleaseId(release.getId());
+                                String dupPkgReleaseId = dupPkg.getReleaseId();
+                                String relId = release.getId();
+                                if (!relId.equals(dupPkgReleaseId) && CommonUtils.isNullEmptyOrWhitespace(dupPkgReleaseId)) {
+                                    /* check if duPkg is orphan pkg or not */
```
Comment (afsahsyeda) [inline backend/src-common/src/main/java/org/eclipse/sw360/cyclonedx/CycloneDxBOMImporter.java:652]: This comment is not required.

File: backend/src-common/src/main/java/org/eclipse/sw360/cyclonedx/CycloneDxBOMImporter.java [hunk 4]
```diff
@@ -646,10 +646,14 @@ private Map<String, String> importAllComponentsAsPackages(Map<String, List<org.c
...
+                                    dupPkg.setReleaseId(relId);
                                     packageDatabaseHandler.updatePackage(dupPkg, user);
+                                    log.info("Release Id linked to orphan pkg : ",relId);
```
Comment (afsahsyeda) [inline backend/src-common/src/main/java/org/eclipse/sw360/cyclonedx/CycloneDxBOMImporter.java:655]: This info is redundant.

**Review by afsahsyeda — CHANGES_REQUESTED** [review]

**Comment by sameed20** [comment]
Test Successful
