### PR TITLE
fix(rest): update clearing request after editing in request tab.

### LINKED ISSUE #3757: fix(Rest): Clearing request update failure.
### Description

Open any clearing request, edit and save - Save failure.

#### How to reproduce

Login as admin, navigate to Request tab find any open clearing requests and edit and save.

#### Screenshots ( if applicable )

Image

### PR DESCRIPTION
**Pull request by nikkuma7**
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

> Please provide a summary of your changes here.
> * Which issue is this pull request belonging to and how is it solving it? (*Refer to issue here*)
> * Did you add or update any new dependencies that are required for your change?

Fixes: Closes #3757 

### How To Test?
1. Navigate to the **Request** tab
2. Select any Clearing Request (CR) from the list
3. Click the **Edit** button to open the request in edit mode
4. Make changes to the clearing request fields (eg. priority)
5. Click the **Save** button
> How should these changes be tested by the reviewer?
> Have you implemented any additional tests?

### Checklist
Must:
- [ ] All related issues are referenced in commit messages and in PR

### CODE REVIEW

**Comment by GMishx** [comment]
@nikkuma7 Exposing the TException is making the test cases fail. Please recheck the logic of test cases
https://github.com/eclipse-sw360/sw360/actions/runs/22389872854/job/64808870169?pr=3756#step:13:6396

File: rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/clearingrequest/ClearingRequestController.java [hunk 1]
```diff
@@ -408,7 +408,7 @@ public ResponseEntity<HalResource<ClearingRequest>> patchClearingRequest(
                         throw new BadRequestClientException("Invalid agreed clearing date requested");
                     }
                 } else {
-                    throw new AccessDeniedException("Update not allowed for field Agreed Clearing Date with user role");
+                    throw new BadRequestClientException("Update not allowed for field Agreed Clearing Date with user role");
```
Comment (GMishx) [inline rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/clearingrequest/ClearingRequestController.java]: No, this should be a `AccessDeniedException`.

File: rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/clearingrequest/ClearingRequestController.java [hunk 2]
```diff
@@ -419,19 +419,30 @@ public ResponseEntity<HalResource<ClearingRequest>> patchClearingRequest(
             HalResource<ClearingRequest> halClearingRequest = createHalClearingRequestWithAllDetails(clearingRequest, sw360User, true);
 
             if (updateCRStatus == RequestStatus.ACCESS_DENIED) {
-                throw new AccessDeniedException("Edit action is not allowed for this user role");
+                throw new BadRequestClientException("Edit action is not allowed for this user role");
```
Comment (GMishx) [inline rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/clearingrequest/ClearingRequestController.java]: No, this should be a `AccessDeniedException`.

File: rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/clearingrequest/ClearingRequestController.java [hunk 3]
```diff
@@ -419,19 +419,30 @@ public ResponseEntity<HalResource<ClearingRequest>> patchClearingRequest(
...
             }
 
             return new ResponseEntity<>(halClearingRequest, HttpStatus.OK);
-        } catch (Exception e) {
+        } catch (AccessDeniedException e) {
+            log.error("Access denied in clearing request update for id {}: {}", id, e.getMessage());
+            throw new BadRequestClientException(e.getMessage(), e);
```
Comment (GMishx) [inline rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/clearingrequest/ClearingRequestController.java]: No, this should be a `AccessDeniedException`.

**Comment by GMishx** [comment]
@nikkuma7 , please fix the test cases. Do not change the exception as per the test-case.

**Review by GMishx — APPROVED** [review]
Changes looks good.
