### PR TITLE
fix(users): :Update differing externalId in getByEmailOrExternalId

### LINKED ISSUE #358: SSOAutoLogin: Update Differing Liferay User's External Id
The SSOAutoLogin updates the Liferay user's email, if the user was not found by email, but by external id (see `SSOAutoLogin.updateLiferayUserEmailIfNecessary()`)

Experience shows that it may happen that a Liferay user has an incorrect (most often missing) external id. In these cases, it makes sense to update the external id. Otherwise, if the user changes the email, then the account cannot be found in Liferay neither by email, nor by external id and yet creation of the new user account will probably fail due to non-unique screen name.

### PR DESCRIPTION
**Pull request by manhuu14**
When a user is found by email but has a missing or incorrect externalId, the externalId is now automatically updated in the database.

This prevents login failures when a user changes their email address, which previously resulted in the account being unreachable by both email and externalId lookups.

Fixes #358

### CODE REVIEW

File: backend/users/src/main/java/org/eclipse/sw360/users/UserHandler.java [hunk 1]
```diff
@@ -123,6 +123,20 @@ public User getByEmailOrExternalId(String email, String externalId) throws TExce
         if (user != null && user.isDeactivated()) {
             return null;
         }
+        if (user != null
+                && externalId != null
+                && !externalId.isEmpty()) {
+            String currentExternalId = user.getExternalid();
+            if (currentExternalId == null
+                    || currentExternalId.isEmpty()
+                    || !currentExternalId.equals(externalId)) {
```
Comment (GMishx) [inline backend/users/src/main/java/org/eclipse/sw360/users/UserHandler.java]: Can be simplified with `CommonUtils.isNullEmptyOrWhitespace``

**Review by GMishx — CHANGES_REQUESTED** [review]
In majority of the cases, the function `getByEmailOrExternalId()` is called as `getByEmailOrExternalId(email, email)`. In such cases, a valid external ID will be updated incorrectly. Please check the same.

File: backend/users/src/main/java/org/eclipse/sw360/users/UserHandler.java (hunk 1 above)
Comment (manhuu14) [reply backend/users/src/main/java/org/eclipse/sw360/users/UserHandler.java]: @GMishx  Just now i fixed Please take a look on this one Thank You!

**Comment by manhuu14** [comment]
@GMishx  have a look on this one. if any suggestion i'll do it Thank You!

**Review by GMishx — DISMISSED** [review]
LGTM
