### PR TITLE
fix(rest): allow external license references in release updates

### LINKED ISSUE #3520: Make PATCH Release endpoint more resilient
### Description

From user:\
“Edit Release” works.\
You can enter links, upload attachments etc.\
But when you click “Update”, then you get an error message “License with ids \[GNU General Public License, version 2 with the GNU Classpath Exception\] does not exist in SW360 database", even if this license is not contained in the uploaded files.

Please describe your issue in few words here.

#### How to reproduce

Describe the bug and list the steps you used when the issue occurred.

#### Screenshots ( if applicable )

Add screenshots to help explain your problem.

### Versions

* Docker version OR
* Last commit id on main

#### SW360 logs

* With docker through `docker logs sw360`
* From bare metal / vm install system under /var/log/sw360/sw360.log and /var/log/tomcat/error.log

### PR DESCRIPTION
**Pull request by nikkuma7**
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

> Please provide a summary of your changes here.
> * Which issue is this pull request belonging to and how is it solving it? (*Refer to issue here*)
> * Did you add or update any new dependencies that are required for your change?

Closes #3520 

### How To Test?
PATCH: http://localhost:8080/resource/api/releases/release{id}
Body: example

{
  "mainLicenseIds": [
    "GNU General Public License, version 2 with the GNU Classpath Exception"
  ],
  "name": "Test Release Update"
}

> How should these changes be tested by the reviewer?
> Have you implemented any additional tests?

### Checklist
Must:
- [ ] All related issues are referenced in commit messages and in PR

### CODE REVIEW

File: rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/RestControllerHelper.java [hunk 1]
```diff
@@ -573,17 +584,32 @@ private HalResource<License> addEmbeddedLicense(String licenseId) {
...
+                return halLicense;
+            } else {
+                LOGGER.error("cannot create self link for license with id: " + licenseId, e);
+                embeddedLicense.setShortname(licenseId);
+                embeddedLicense.setOSIApproved(Quadratic.NA);
+                embeddedLicense.setFSFLibre(Quadratic.NA);
+                embeddedLicense.setChecked(false);
+                embeddedLicense.setFullname(null);
+                return halLicense;
+            }
```
Comment (GMishx) [inline rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/RestControllerHelper.java]: The branch for `if` and `else` is exactly the same with only exception about fullname being `null` in `else` case. Instead, can the dummy `embeddedLicense` be returned like in `ResourceNotFoundException` case?

File: rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/RestControllerHelper.java [hunk 2]
```diff
@@ -806,20 +840,118 @@ public License convertLicenseFromRequest(Map<String, Object> reqBodyMap, License
...
         }
+
         if (!licenseIncorrect.isEmpty()) {
-            throw new BadRequestClientException("License with ids " + licenseIncorrect + " does not exist in SW360 database.");
+            String errorMsg = fieldName + " with ids " + licenseIncorrect + " does not exist in SW360 database.";
+            if (!licenseWarnings.isEmpty()) {
+                errorMsg += " Note: External license references " + licenseWarnings + " were allowed.";
+            }
+            LOGGER.error("License validation failed: {}", errorMsg);
+            throw new BadRequestClientException(errorMsg);
```
Comment (GMishx) [inline rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/RestControllerHelper.java]: The idea of being "Resilient" is **not to** throw exceptions. But ignore bad entries while entering them to DB and notify user. Throwing an error here will still prevent the user from storing the entire release update even if it contains one bad license.

File: rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/RestControllerHelper.java [hunk 3]
```diff
@@ -806,20 +840,118 @@ public License convertLicenseFromRequest(Map<String, Object> reqBodyMap, License
...
+
+        return isMatchingConfigurablePatterns(normalizedId) ||
+               isLongDescriptiveName(normalizedId);
+    }
+
+    /**
+     * Check against configurable license patterns from application properties
+     * This is now more conservative to avoid false positives with standard SPDX identifiers
+     */
+    private boolean isMatchingConfigurablePatterns(String normalizedId) {
```
Comment (GMishx) [inline rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/RestControllerHelper.java]: This function does not make sense to me. Can you please explain why are we looking for Microsoft/Oracle/Google etc in the license names and calling them external licenses?

File: rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/RestControllerHelper.java [hunk 4]
```diff
@@ -806,20 +840,118 @@ public License convertLicenseFromRequest(Map<String, Object> reqBodyMap, License
...
+        }
+
+        return false;
+    }
+
+    /**
+     * Check if it's likely a long descriptive name from external sources
+     * Only very long names are considered external to be conservative
+     */
+    private boolean isLongDescriptiveName(String normalizedId) {
```
Comment (GMishx) [inline rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/RestControllerHelper.java]: Same with this function. Why are we looking for arbitrary value of `40` in name lenght?
