### PR TITLE
bug(spdx): fixed spdx import format

### LINKED ISSUE #3249: SPDX Import Format
### Description

Hitting endpoint /licences/import/SPDX returns 200 but no response body.

#### Screenshots ( if applicable )

Image

### PR DESCRIPTION
**Pull request by ritankarsaha**
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

## Summary 

- on hitting endpoint /licences/import/SPDX returns 200 with a response body.

Issue: #3249 

### Suggest Reviewer
@GMishx 
@amritkv 
@rudra-superrr 

### How To Test?
- can test via swagger or curl after build
- tested via curl 

Curl Command -- 
```bash
curl -v --max-time 30 -X 'POST' \
    'http://127.0.0.1:8080/resource/api/licenses/import/SPDX' \
    -H 'accept: application/json' \
    -H 'Content-Type: application/json' \
    -H 'Authorization: Basic YWRtaW5Ac3czNjAub3JnOjEyMzQ1' \
    -d '{}'
```

Output Response Body --
```bash
{
  "requestStatus" : "SUCCESS",
  "totalAffectedElements" : 699,
  "totalElements" : 699,
  "message" : "SPDX license has imported successfully",
  "setTotalAffectedElements" : false,
  "setTotalElements" : false,
  "setMessage" : true,
  "setRequestStatus" : true
* Connection #0 to host 127.0.0.1 left intact
```

Fixes #3249 

### Checklist
Must:
- [x] All related issues are referenced in commit messages and in PR

### CODE REVIEW

File: rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/license/LicenseController.java [hunk 1]
```diff
@@ -455,10 +456,14 @@ public ResponseEntity deleteAllLicense() throws TException {
...
     @RequestMapping(value = LICENSES_URL + "/import/SPDX", method = RequestMethod.POST)
-    public ResponseEntity importSPDX() throws TException {
+    public ResponseEntity<RequestSummary> importSPDX() throws TException {
         User sw360User = restControllerHelper.getSw360UserFromAuthentication();
-        licenseService.importSpdxInformation(sw360User);
-        return new ResponseEntity<>(HttpStatus.OK);
+        RequestSummary requestSummary = licenseService.importSpdxInformation(sw360User);
+        requestSummary.setMessage("SPDX license has imported successfully");
+        requestSummary.unsetTotalAffectedElements();
+        requestSummary.unsetTotalElements();
```
Comment (GMishx) [inline rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/license/LicenseController.java]: Why do we need to unset these values? Can you please help me understand?

Comment (ritankarsaha) [reply rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/license/LicenseController.java]: resolved, it now gives full output with proper logs in the catalina.

**Review by GMishx — APPROVED** [review]
LGTM

**Comment by GMishx** [comment]
@deo002 please help testing the fix.

**Comment by ritankarsaha** [comment]
@GMishx fixed the test error 🫡 , it's returning value now but we were still doing doNothing()

**Comment by rudra-superrr** [comment]
Testing was successful, 
image

There’s a JSON error showing up while importing or manually adding licenses. Maybe we can create separate issue for this.
image

**Comment by ritankarsaha** [comment]
> Testing was successful, image
> 
> There’s a JSON error showing up while importing or manually adding licenses. Maybe we can create separate issue for this. image

should I make a new issue for that then and tackle that there ?  @rudra-superrr 

Also should I rebase and update the branch from main ?

**Comment by rudra-superrr** [comment]
Yes, to both questions.

**Comment by ritankarsaha** [comment]
> Yes, to both questions.

okiee

**Review by GMishx — APPROVED** [review]
