### PR TITLE
Project: Missing Export Spreadsheet Download Email.

### LINKED ISSUE #3650: Project: Missing Export Spreadsheet Download Email.
### Description

No email is received to download the 'Export Spreadsheet' when initiated for either a standalone project or a project that includes linked projects.

Please describe your issue in few words here.

#### How to reproduce

Describe the bug and list the steps you used when the issue occurred.

#### Screenshots ( if applicable )

Add screenshots to help explain your problem.

### Versions

* Docker version OR
* Last commit id on main

#### SW360 logs

* With docker through `docker logs sw360`
* From bare metal / vm install system under /var/log/sw360/sw360.log and /var/log/tomcat/error.log

### PR DESCRIPTION
**Pull request by nikkuma7**
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

> Please provide a summary of your changes here.
> * Which issue is this pull request belonging to and how is it solving it? (*Refer to issue here*)
> * Did you add or update any new dependencies that are required for your change?

Closes #3650 

### How To Test?

1. GET request for project report without linked releases means project only:
http://localhost:8080/resource/api/reports?module=projects&projectId={projectId}

2. GET request for project report with linked releases:
http://localhost:8080/resource/api/reports?module=projects&projectId={projectId}&withlinkedreleases=true

3. Verify the file is created locally at: /tmp/{loginId}/ (e.g., for user admin@sw360.org, the path would be /tmp/admin@sw360.org/)

4. Check the console logs to find the download link for the generated report.

Note: Replace {projectId} with an actual project ID from your SW360 instance.

> How should these changes be tested by the reviewer?
> Have you implemented any additional tests?

### Checklist
Must:
- [ ] All related issues are referenced in commit messages and in PR

### CODE REVIEW

File: libraries/exporters/src/main/java/org/eclipse/sw360/exporter/ExcelExporter.java [hunk 1]
```diff
@@ -85,11 +85,11 @@ public InputStream makeExcelExport(List<T> documents) throws IOException, SW360E
     public String makeExcelExportForProject(List<T> documents, User user) throws IOException, SW360Exception {
         final SXSSFWorkbook workbook = new SXSSFWorkbook();
         String token = UUID.randomUUID().toString();
-        String filePath = TMP_EXPORTEDFILES + user.getEmail() + SLASH;
+        String filePath = TMP_EXPORTEDFILES + user.getEmail() + SLASH + "file" + SLASH;
```
Comment (GMishx) [inline libraries/exporters/src/main/java/org/eclipse/sw360/exporter/ExcelExporter.java:88]: Any reason to add the `/file/` to the file path?

Comment (nikkuma7) [reply libraries/exporters/src/main/java/org/eclipse/sw360/exporter/ExcelExporter.java:88]: it creates a file in the location :/tmp/file/file_name
 
i provided a file because we understood it should be placed the /tmp/file location and i verified that it was created in the same location.
