### PR TITLE
fix: make project mainlineState field required

### LINKED ISSUE #3395: Project Mainline State Field Required
### Description

There is no field for Project Mainline State in the api response of /projects/{id}/licenseClearing. It is required for the License Clearing tables in Project details tab.

#### Screenshots

Image

### PR DESCRIPTION
**Pull request by taanvi2205**
Added projectMainlineState field to the API response. This field represents the mainline state of a release within a specific project, which is different from the release's own mainlineState.

Issue: Fixes #3395

### How to Test
1. Create a project and link a release to it
2. Call API: GET /projects/{id}/licenseClearing?transitive=true
3. Verify projectMainlineState appears in response under linkedReleases 

### Checklist
Must:
- [x] All related issues are referenced in commit messages and in PR

### CODE REVIEW

File: rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/JacksonCustomizations.java
Comment (GMishx) [inline rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/JacksonCustomizations.java:1]: Please revert changes in this class. Nothing seems to be relevant for this PR.

File: rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/RestControllerHelper.java [hunk 1]
```diff
@@ -9,6 +9,7 @@
  */
 package org.eclipse.sw360.rest.resourceserver.core;
 
+import org.eclipse.sw360.datahandler.thrift.MainlineState;
```
Comment (GMishx) [inline rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/RestControllerHelper.java]: Irrelevant chagnes?

**Review by GMishx — CHANGES_REQUESTED** [review]
Minor cleanup required. Rest looks good.

File: rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/JacksonCustomizations.java
Comment (taanvi2205) [reply rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/JacksonCustomizations.java]: @GMishx I added these because I thought the new transient field projectMainlineState in Release (components.thrift:259) would need the corresponding setter/isSet methods to be excluded from Jackson serialization similar to how other fields are handled in this file.

Comment (taanvi2205) [reply rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/core/JacksonCustomizations.java:1]: @GMishx Thanks for the review I added these because I think Thrift generates setProjectMainlineState() and projectMainlineStateIsSet() methods for the new field, and without adding them to JsonIgnoreProperties, Jackson might include them as extra properties in the API response. That's why I followed the same pattern as other fields in this file. Let me know if I'm misunderstanding

**Comment by taanvi2205** [comment]
@GMishx please review it now
