### PR TITLE
fix(rest): add vendor existence validation in getReleases endpoint

### LINKED ISSUE #3205: `VendorController.getReleases()` doesn't validate vendor existence before retrieving releases
## Description
The endpoint in doesn't validate whether a vendor with the given ID exists before attempting to retrieve its releases. This leads to inconsistent API behavior and poor client experience. [getReleases()](https://github.com/eclipse-sw360/sw360/blob/18ac76e0c021707e75112d319143dd96318ebffb/rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/vendor/VendorController.java#L144C66-L144C77)

## Current Behavior
- **Request:** `GET /vendors/{non-existent-id}/releases`
- **Response:** `204 No Content`
- **Issue:** Client cannot distinguish between "vendor exists but has no releases" vs "vendor doesn't exist"

https://github.com/user-attachments/assets/a15e6467-7f86-4a47-84f0-8de99500abc1

### PR DESCRIPTION
**Pull request by Mohamed-hanfy**
this PR fixes a critical API inconsistency in the VendorController.getReleases() method. Previously, the endpoint would return 204 No Content for non-existent vendor IDs, making it impossible for clients to distinguish between "vendor exists but has no releases" and "vendor doesn't exist".

closes #3205

### CODE REVIEW

File: rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/vendor/VendorController.java [hunk 1]
```diff
@@ -145,6 +145,9 @@ public ResponseEntity<CollectionModel<EntityModel<Release>>> getReleases(
             @Parameter(description = "The id of the vendor to get.")
             @PathVariable("id") String id
     ) throws SW360Exception {
+        if(vendorService.getVendorById(id) == null){
+            throw new ResourceNotFoundException("Vendor with id " + id + " not found.");
+        }
         User sw360User = restControllerHelper.getSw360UserFromAuthentication();
         restControllerHelper.throwIfSecurityUser(sw360User);
```
Comment (GMishx) [inline rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/vendor/VendorController.java]: Ah, a minor security issue. User with "Security User" role and hit this endpoint with different IDs and see a `404` or `403` based on vendor exists or not.

Just move the 3 lines bellow `restControllerHelper.throwIfSecurityUser(sw360User);` test and we are good to go.

Comment (Mohamed-hanfy) [reply rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/vendor/VendorController.java]: DONE

**Review by GMishx — APPROVED** [review]
LGTM
