### PR TITLE
fix(rest): Restructuring of the response to Delete a License Type API.

### LINKED ISSUE #3192: Admin (License Type) : Need info about the usage of `License Types`
### Description

Before going to delete a `License Type`, we need to know about its usages. Like whether this license type is being used by any license or not. If it is being used by any license, we can't delete it.

In response we need : 

- Whether current license type is being used (`true` / `false`) ?
- If it is used by some licenses. then the total count of such licenses

#### Screenshots ( if applicable )

Add screenshots to help explain your problem.

Image

### PR DESCRIPTION
**Pull request by nikkuma7**
…sponse

[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

> Please provide a summary of your changes here.
> * Which issue is this pull request belonging to and how is it solving it? (*Refer to issue here*)
> * Did you add or update any new dependencies that are required for your change?

Closes #3192

### How To Test
Delete: http://localhost:8080/resource/api/licenseTypes/5c2f90c4f15d2c92a91ff880c00021
First, create a License Type and then assign it to a License. After that, try to delete the License Type using its ID — it will not be allowed because it is in use. However, if the License Type is not assigned to any License, you will be able to delete it.
image

image

> How should these changes be tested by the reviewer?
> Have you implemented any additional tests?

### Checklist
Must:
- [ ] All related issues are referenced in commit messages and in PR

### CODE REVIEW

File: rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/license/LicenseController.java [hunk 1]
```diff
@@ -562,6 +562,19 @@ public ResponseEntity deleteLicenseType(
...
+        Map<String, String> response = new HashMap<>();
+        response.put("status", status.name());
+
+        switch (status) {
+        case SUCCESS:
+            response.put("message", "License type deleted successfully.");
+            return ResponseEntity.ok(response);
+        case IN_USE:
+            response.put("message", "Cannot delete license type because it is currently in use.");
+            return ResponseEntity.status(HttpStatus.CONFLICT).body(response);
```
Comment (GMishx) [inline rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/license/LicenseController.java]: Please throw appropriate exception:
```java
throw new HttpClientErrorException(HttpStatus.CONFLICT, "Cannot delete license type because it is currently in use");
```

File: rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/license/LicenseController.java [hunk 2]
```diff
@@ -562,6 +562,19 @@ public ResponseEntity deleteLicenseType(
...
+        default:
+            response.put("message", "Failed to delete license type due to unknown reason.");
+            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).body(response);
```
Comment (GMishx) [inline rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/license/LicenseController.java]: Please add a case for `RequestStatus.ACCESS_DENIED` and throw `AccessDeniedException`

File: backend/licenses-core/src/main/java/org/eclipse/sw360/licenses/db/LicenseDatabaseHandler.java [hunk 3]
```diff
@@ -1164,21 +1164,29 @@ public RequestStatus deleteObligations(String id, User user) throws SW360Excepti
...
-            if (checkLicenseTypeInUse(id) > 0) {
-                return RequestStatus.IN_USE;
-            }
-            licenseTypeRepository.remove(licenseType);
-            return RequestStatus.SUCCESS;
-        } else {
-            log.error(user + " does not have the permission to delete license type.");
+        if (licenseType == null) {
+            log.warn("License type not found with ID: {}", id);
+            return RequestStatus.FAILURE;
```
Comment (GMishx) [inline backend/licenses-core/src/main/java/org/eclipse/sw360/licenses/db/LicenseDatabaseHandler.java]: `RequestStatus.INVALID_INPUT` would be more appropriate response as `FAILURE` can be a 500 error as well.

File: rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/license/LicenseController.java (hunk 2 above)
Comment (GMishx) [inline rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/license/LicenseController.java]: If using `RequestStatus.INVALID_INPUT` in handler class, throw `ResourceNotFoundException`

File: rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/license/LicenseController.java [hunk 4]
```diff
@@ -562,6 +562,19 @@ public ResponseEntity deleteLicenseType(
...
+        }
```
Comment (GMishx) [inline rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/license/LicenseController.java]: Please fix indentation.

**Review by GMishx — CHANGES_REQUESTED** [review]

**Comment by nikkuma7** [comment]
Comment Addressed.

File: rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/license/LicenseController.java [hunk 5]
```diff
@@ -562,6 +564,29 @@ public ResponseEntity deleteLicenseType(
         User sw360User = restControllerHelper.getSw360UserFromAuthentication();
         RequestStatus status = licenseService.deleteLicenseType(id, sw360User);
 
-        return ResponseEntity.ok("License type deleted successfully: " + status.name());
+        Map<String, String> response = new HashMap<>();
+        response.put("status", status.name());
```
Comment (GMishx) [inline rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/license/LicenseController.java]: Variable is created but never used. Please remove.

**Review by GMishx — CHANGES_REQUESTED** [review]
