### PR TITLE
fix(report) #3836: respect withSubProject for licenseInfo reports 

### LINKED ISSUE #3903: Missing implementation of withSubProject while generating LicenseInfo reportbugSomething isn't working
### Description

The withSubProject request parameter in the SW360ReportController is ignored when generating a LicenseInfo report. There is a stale 'TODO' in the controller , and the backend service Sw360ProjectService uses a hardcoded true value.

#### How to reproduce

- Make a REST call to genearte a LicenseInfo report.
- Pass te parameter : withSubProject = false
- The generated report still includes components

**Location:**
Controller: rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/report/SW360ReportController.java

Service: /rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/project/Sw360ProjectService.java

**Problem :**

```
List mappedProjectLinks = projectService.createLinkedProjects(sw360Project,
projectService.filterAndSortAttachments(SW360Constants.LICENSE_INFO_ATTACHMENT_TYPES), true, true, sw360User);
```

### PR DESCRIPTION
**Pull request by YianZhao**
### What changed
- Respect `withSubProject` in `licenseInfo` report service path.
- Keep `exportCreateProjectClearingReport` behavior unchanged by forcing `withSubProject=true`.

### How To Test?
You can test it with the project with the sub-project
and also link the release, and then for the compare the result with true and false in `withSubProject`
image

Closes #3903

### CODE REVIEW

File: rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/report/SW360ReportController.java [hunk 1]
```diff
@@ -258,6 +257,7 @@ private void exportProjectCreateClearingRequest(
             HttpServletResponse response, User sw360User, String module, String projectId, SW360ReportBean reportBean
     ) throws SW360Exception {
         try {
+            reportBean.setWithSubProject(true);
```
Comment (GMishx) [inline rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/report/SW360ReportController.java]: According to my understanding, this is called as hard-coding and not respecting user's input. Did I miss something?

Comment (YianZhao) [reply rest/resource-server/src/main/java/org/eclipse/sw360/rest/resourceserver/report/SW360ReportController.java]: You’re right — that line was hard-coded and it was pushed by mistake in an earlier revision.

I’ve removed it now and updated the logic to respect the user's input. I also tested it locally, and the output is now correct for both `withSubProject=true` and `withSubProject=false`.

Thanks for pointing this out.

**Review by GMishx — APPROVED** [review]
LGTM

**Comment by GMishx** [comment]
@YianZhao please squash your commits into one as they solve a single logical problem and keeps the history clean in case a revert was needed.

**Comment by YianZhao** [comment]
@GMishx Thanks for the suggestion. I rebased on the latest upstream/main and squashed the related changes into a single commit.
